model {
  file: "model.sdf"
  file_format {
    version {
      major: 1
      minor: 6
    }
    name: "sdf"
  }
}
name: "ctu_cras_norlab_x500_sensor_config_2"
description: "CTU-CRAS-NORLAB X500 UAV \n    Sensor configuration:\n    - 3D medium range lidar Ouster OS0-64\n    - frontward Basler dart daA1600-60um with DSL165A lens (RGB camera)\n    - standard SubT IMU"
authors {
  name: "Matej Petrlik"
  email: "matej.petrlik@fel.cvut.cz"
}

